export const SETTINGS_TEACHER = "SETTINGS_TEACHER";
export const DASHEBOARD_TEACHER = "DASHEBOARD_TEACHER";
export const DASHEBOARD_STUDENT = "DASHEBOARD_STUDENT";
export const SETTINGS_STUDENT = "SETTINGS_STUDENT";

//export Api back end
export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
