export const accordionStyles = {
  header: {
    fontWeight: "bold",
    backgroundColor: "#f8f9fa",
    color: "#343a40",
    padding: "15px 20px",
    borderBottom: "1px solid #ced4da",
    borderRadius: "5px",
    transition: "background-color 0.2s ease, color 0.2s ease",
    fontSize: "1rem",
  },
  headerActive: {
    backgroundColor: "#007bff",
    color: "#fff",
  },
  body: {
    backgroundColor: "#ffffff",
    padding: "20px",
    borderRadius: "0 0 5px 5px",
    border: "1px solid #ced4da",
    borderTop: "none",
    fontSize: "0.9rem",
    lineHeight: "1.5",
  },
  card: {
    border: "none",
    marginBottom: "15px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    borderRadius: "5px",
  },
  updateButton: {
    marginTop: "10px",
    backgroundColor: "#28a745",
    borderColor: "#28a745",
    color: "#fff",
    borderRadius: "5px",
    padding: "8px 16px",
    transition: "background-color 0.2s ease",
  },
  deleteButton: {
    marginTop: "10px",
    backgroundColor: "#dc3545",
    borderColor: "#dc3545",
    color: "#fff",
    borderRadius: "5px",
    padding: "8px 16px",
    transition: "background-color 0.2s ease",
    marginLeft: "10px",
  },
};
