// Styles en ligne
export const styles = {
  tabsContainer: {
    marginBottom: '20px',
  },
  addButton: {
    marginLeft: 'auto',
    backgroundColor: '#007bff',
    color: '#ffffff',
    border: 'none',
    padding: '10px 15px',
    borderRadius: '0.375rem',
    fontWeight: 'bold',
    fontSize: '1rem',
    display: 'flex',
    alignItems: 'center',
    marginBottom: '15px',
  },
  cardHeader: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    color: 'black',
    fontWeight: 'bold',
    fontSize: '1.1rem',
    padding: '20px 24px',
    borderBottom: '1px solid #007bff',
  },
  card: {
    backgroundColor: '#f1f1f1',
    borderRadius: '12px',
    padding: '25px',
    border: 'none',
    marginBottom: '30px',
  },
  listItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '14px 24px',
    borderBottom: '1px solid #e0e0e0',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    marginBottom: '15px',
    boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.05)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
  },
  iconContainer: {
    marginRight: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '50px',
    height: '50px',
    backgroundColor: '#f0f0f0',
    borderRadius: '50%',
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#007bff',
  },
  name: {
    flexGrow: 1,
    fontWeight: '600',
    color: '#333',
    fontSize: '1rem',
  },
  detail: {
    color: '#6c757d',
    marginRight: '20px',
    fontSize: '0.95rem',
  },
  date: {
    color: '#999',
    fontSize: '0.9rem',
    marginRight: '20px',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: 'auto',
  },
  button: {
    color: '#6c757d',
    border: 'none',
    background: 'none',
    padding: '0',
    margin: '0 8px',
    fontSize: '1.2rem',
    transition: 'color 0.2s ease',
  },
};