// Styles en ligne avec !important
export const styles = {
  tabsContainer: {
    marginBottom: '20px !important',
  },
  addButton: {
    marginLeft: 'auto !important',
    backgroundColor: '#007bff !important',
    color: '#ffffff !important',
    border: 'none !important',
    padding: '10px 15px !important',
    borderRadius: '0.375rem !important',
    fontWeight: 'bold !important',
    fontSize: '1rem !important',
    display: 'flex !important',
    alignItems: 'center !important',
    marginBottom: '15px !important',
  },
  cardHeader: {
    backgroundColor: 'rgba(255, 255, 255, 0.5) !important',
    color: 'black !important',
    fontWeight: 'bold !important',
    fontSize: '1.1rem !important',
    padding: '20px 24px !important',
    borderBottom: '1px solid #007bff !important',
  },
  card: {
    backgroundColor: '#f1f1f1 !important',
    borderRadius: '12px !important',
    padding: '25px !important',
    border: 'none !important',
    marginBottom: '30px !important',
  },
  listItem: {
    display: 'flex !important',
    alignItems: 'center !important',
    padding: '14px 24px !important',
    borderBottom: '1px solid #e0e0e0 !important',
    backgroundColor: '#ffffff !important',
    borderRadius: '12px !important',
    marginBottom: '15px !important',
    boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.05) !important',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease !important',
  },
  iconContainer: {
    marginRight: '20px !important',
    display: 'flex !important',
    alignItems: 'center !important',
    justifyContent: 'center !important',
    width: '50px !important',
    height: '50px !important',
    backgroundColor: '#f0f0f0 !important',
    borderRadius: '50% !important',
    fontSize: '20px !important',
    fontWeight: 'bold !important',
    color: '#007bff !important',
  },
  name: {
    flexGrow: 1,
    fontWeight: '600 !important',
    color: '#333 !important',
    fontSize: '1rem !important',
  },
  detail: {
    color: '#6c757d !important',
    marginRight: '20px !important',
    fontSize: '0.95rem !important',
  },
  date: {
    color: '#999 !important',
    fontSize: '0.9rem !important',
    marginRight: '20px !important',
  },
  actions: {
    display: 'flex !important',
    alignItems: 'center !important',
    marginLeft: 'auto !important',
  },
  button: {
    color: '#6c757d !important',
    border: 'none !important',
    background: 'none !important',
    padding: '0 !important',
    margin: '0 8px !important',
    fontSize: '1.2rem !important',
    transition: 'color 0.2s ease !important',
  },
};
